### PR TITLE
Docs/sarah

### PR DESCRIPTION
**Pull request by sarahcatherine311**
edited the branch name lol

### CODE REVIEW

**Comment by grace-joh** [comment]
hi! testing this comment.

**Review by grace-joh — DISMISSED** [review]
Let's add one more 'blah' on line 9.

**Comment by grace-joh** [comment]
Good to merge now?

**Comment by grace-joh** [comment]
Nice! Thanks for working it out with me :)

**Comment by sarahcatherine311** [comment]
So we are supposed to create a new branch every time we edit something?
Tells me this branch can be safely deleted. I guess that would be why she named it docs/name because she is making it clear that this pull request is changing the readme file?

**Comment by grace-joh** [comment]
Yeah, my understanding is that we make a branch so that changes can be outside of the working main branch, even if it's just a simple addition or fix. Just to keep the main branch version safe?
When we add a branch, all the commits made to the branch are added to the list of commits of the main. So at this point, the current main is past main + branch.  But even, after the merge, the branch is still available to see until we delete it.

**Pull request merged**
